server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: movie
          uri: lb://movie
          predicates:
            - Path=/api/v1/poli/movie/**
        - id: user
          uri: lb://user
          predicates:
            - Path=/api/v1/poli/user/**
        - id: showtime
          uri: lb://showtime
          predicates:
            - Path=/api/v1/poli/showtime/**